### ISSUE TITLE
Leave Chat error

### ISSUE THREAD

**Issue by AngelicHuman** [forevercynical/pymino#1]
Unsupported service. Your client may be out of date. Please update it to the latest version. ({"api:timestamp":"2023-02-17T19:24:15Z","api:statuscode":100,"api:duration":"0.002s","api:message":"Unsupported service. Your client may be out of date. Please update it to the latest version."}).

**Comment by forevercynical** [comment]
Pls provide the function being used

**Comment by AngelicHuman** [comment]
> Pls provide the function being used
u have it already ☠️
